language: csharp
solution: Polaris/Polaris.sln
dotnet: 1.0.0-preview2-003121
mono: none

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty
      sudo: required

script:
  - mkdir bla && cd bla && dotnet new && time dotnet restore && dotnet run
