language: csharp
solution: Polaris/Polaris.sln

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003121
      mono: none
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none

script:
  - cd Polaris && time dotnet restore && dotnet run
